[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"
desc = "mount and unmount drives"

[[mgr.prepend_keymap]]
on = [ "<C-d>" ]
run = "plugin drag"
desc = "Drag and Drop files"

[[mgr.prepend_keymap]]
on = [ "u" ]
run = "plugin restore"
desc = "Open Recent Trash"
