[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"
desc = "mount and unmount drives"

[[mgr.prepend_keymap]]
on = [ "<C-d>" ]
run = "plugin drag"
desc = "Drag and Drop files"

[[mgr.prepend_keymap]]
on = "u"
run = "plugin restore"
desc = "restore last deleted file"

[[mgr.prepend_keymap]]
on   = ["R"]
run  = "plugin rotate-image"
desc = "Rotate images"

[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = "plugin kdenconnect-send"
desc = "Send selected files via KDE Connect"

[[mgr.prepend_keymap]]
on   = [ "e", "c" ]
run  = "plugin git-files"
desc = "Show Git file changes"

### recycle-bin plugin maps

[[mgr.prepend_keymap]]
on = ["g","t"]
run = "plugin recycle-bin open"
desc = "Go to Trash"

[[mgr.prepend_keymap]]
on = ["T","o"]
run = "plugin recycle-bin open"
desc = "Open Trash"

[[mgr.prepend_keymap]]
on = ["T", "e"]
run = "plugin recycle-bin empty"
desc = "Empty Trash"

[[mgr.prepend_keymap]]
on = ["T", "d"]
run = "plugin recycle-bin delete"
desc = "Delete from Trash"

[[mgr.prepend_keymap]]
on = ["T", "D"]
run = "plugin recycle-bin emptyDays"
desc = "Empty by days deleted"

[[mgr.prepend_keymap]]
on = ["T", "r"]
run = "plugin recycle-bin restore"
desc = "Restore from Trash"
